# Generated by Django 2.2 on 2021-04-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newspaper', models.CharField(blank=True, max_length=150, null=True)),
                ('newspaper_image', models.ImageField(blank=True, null=True, upload_to='newspaper')),
            ],
            options={
                'verbose_name': 'Newspaper',
                'verbose_name_plural': 'Newspapers',
                'managed': True,
            },
        ),
    ]
