# Generated by Django 2.2 on 2021-04-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('adtype', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Ad Type',
                'verbose_name_plural': 'Ad Type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'City',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Language',
                'managed': True,
            },
        ),
    ]
